### ISSUE TITLE
TypeError: Cannot read property 'join' of undefined

### ISSUE THREAD

**Issue by BobChubby** [cybertim/SmallBotMatrix#2]
Shortly after calling `client.start()` and loading a few of the events, the client crashes with:
```
error: Uncaught (in promise) TypeError: Cannot read property 'join' of undefined
        response.rooms.join = new Map<string, MatrixRoomEvent>(Object.entries(response.rooms.join));
                                                                                             ^
    at SmallBot.getSync (https://raw.githubusercontent.com/cybertim/SmallBotMatrix/main/lib/SmallBot.ts:127:94)
    at async SmallBot.syncLoop (https://raw.githubusercontent.com/cybertim/SmallBotMatrix/main/lib/SmallBot.ts:61:30)
```
It also appears that userId in client is null in this case as well in case that's related

**Comment by lousando** [comment]
I am also getting this issue. It happens quicker when the handler method is set to do nothing. However, even when it's doing logic, it still fails once it seems to catch up with events.
