### ISSUE TITLE
Reduce console logging

### ISSUE THREAD

**Issue by lousando** [cybertim/SmallBotMatrix#5]
When using the library in a projects, it logs out a lot of messages making it difficult to differentiate between my app's logs and `small-bot`'s. It would be neat if `small-bot-matrix` only logs messages such as `Fetched from 'https://[homeserver]/_matrix/client/r0/sync` when a `DEBUG` env variable is set.

**Comment by enimatek-nl** [comment]
you can always 'override' the default console logger with own logic: https://github.com/enimatek-nl/small-bot-matrix/blob/3574c2e4b68dabc33b0dedddfa03058e9cca3aab/lib/SmallBot.ts#L37
hope this is helpful
